apiVersion: v1
kind: Service
metadata:
  name:  frontend-luis-tasayco-deployment
  namespace: luis-tasayco-namespace
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app:  frontend-luis-tasayco-deployment